In [1]:
# STANDARDS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# CUFFLINKS & PLOTLY
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import cufflinks as cf
init_notebook_mode(connected=True)
cf.go_offline()

In [3]:
df = pd.read_excel(r'C:\Users\krunk\OneDrive\Documents\CPSC 589\Dataset\BBS Dataset.xlsx',sheet_name='ReData')
df.head()

Patient's Age  Item 1  Item 2  Item 3  Item 4  Item 5  Item 6  Item 7  \
0             97       1       0       1       1       1       0       0   
1             88       2       0       1       4       3       2       2   
2             73       3       4       3       2       2       0       2   
3             77       2       3       1       0       4       4       2   
4             65       3       4       1       4       4       2       4   

   Item 8  Item 9  Item 10  Item 11  Item 12  Item 13  Item 14  BBS Sum  \
0       1       1        0        0        0        1        1        8   
1       3       4        0        1        0        4        4       30   
2       3       1        0        1        2        4        3       30   
3       0       1        1        0        2        3        1       24   
4       4       2        1        2        3        3        4       41   

  Assessment of Risk  
0               HIGH  
1             MEDIUM  
2             MEDIUM  
3             MEDIUM  
4                LOW

In [4]:
# SCIKIT SET
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import classification_report,confusion_matrix

In [5]:
rs = 3717

In [6]:
# ALL ITEMS INCLUDED

In [7]:
X = df.drop(['Patient\'s Age','BBS Sum','Assessment of Risk'],axis=1)
y = df['Assessment of Risk']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=rs)

In [8]:
# NO PARAMETER ADJUSTMENT
model = SVC()
model.fit(X_train,y_train)
y_predict = model.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

[[31  0  0]
 [ 0 39  0]
 [ 1  0 36]]
              precision    recall  f1-score   support

        HIGH       0.97      1.00      0.98        31
         LOW       1.00      1.00      1.00        39
      MEDIUM       1.00      0.97      0.99        37

    accuracy                           0.99       107
   macro avg       0.99      0.99      0.99       107
weighted avg       0.99      0.99      0.99       107



In [9]:
# WITH PARAMETER ADJUSTMENT
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001]}
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=0)
grid.fit(X_train,y_train)
grid_predict = grid.predict(X_test)
print('\n')
print(confusion_matrix(y_test,grid_predict))
print(classification_report(y_test,grid_predict))



[[31  0  0]
 [ 0 38  1]
 [ 1  0 36]]
              precision    recall  f1-score   support

        HIGH       0.97      1.00      0.98        31
         LOW       1.00      0.97      0.99        39
      MEDIUM       0.97      0.97      0.97        37

    accuracy                           0.98       107
   macro avg       0.98      0.98      0.98       107
weighted avg       0.98      0.98      0.98       107



In [10]:
# ALL ITEMS WITHOUT PARAMETER ADJUSTMENTS BEST

In [11]:
grid.best_estimator_

SVC(C=1, gamma=0.01)

In [12]:
y_predict = y_predict
ex1 = pd.concat([pd.DataFrame(confusion_matrix(y_test,y_predict,labels=['LOW','MEDIUM','HIGH']),index=['LOW','MEDIUM','HIGH'],columns=['LOW','MEDIUM','HIGH']),
pd.DataFrame(classification_report(y_test,y_predict,labels=['LOW','MEDIUM','HIGH'],output_dict=True)).transpose()],axis=1)
ex1.set_index([['Original','Original','Original','Original','Original','Original'],ex1.index],inplace=True)
ex1

LOW  MEDIUM  HIGH  precision    recall  f1-score  \
Original LOW           39.0     0.0   0.0   1.000000  1.000000  1.000000   
         MEDIUM         0.0    36.0   1.0   1.000000  0.972973  0.986301   
         HIGH           0.0     0.0  31.0   0.968750  1.000000  0.984127   
         accuracy       NaN     NaN   NaN   0.990654  0.990654  0.990654   
         macro avg      NaN     NaN   NaN   0.989583  0.990991  0.990143   
         weighted avg   NaN     NaN   NaN   0.990946  0.990654  0.990664   

                          support  
Original LOW            39.000000  
         MEDIUM         37.000000  
         HIGH           31.000000  
         accuracy        0.990654  
         macro avg     107.000000  
         weighted avg  107.000000

In [13]:
# HIGH CORR TOP 4 PICKED 9,11,10,5 (4 TOTAL ITEMS)

In [14]:
X = df[['Item 5','Item 9','Item 10','Item 11']]
y = df['Assessment of Risk']
text = 'HIGH CORR TOP 4 PICKED 9,11,10,5 (4 TOTAL ITEMS)'

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=rs)

In [15]:
# NO PARAMETER ADJUSTMENT
model = SVC()
model.fit(X_train,y_train)
y_predict = model.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

[[29  0  2]
 [ 0 34  5]
 [ 0  5 32]]
              precision    recall  f1-score   support

        HIGH       1.00      0.94      0.97        31
         LOW       0.87      0.87      0.87        39
      MEDIUM       0.82      0.86      0.84        37

    accuracy                           0.89       107
   macro avg       0.90      0.89      0.89       107
weighted avg       0.89      0.89      0.89       107



In [16]:
# WITH PARAMETER ADJUSTMENT
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001]}
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=0)
grid.fit(X_train,y_train)
grid_predict = grid.predict(X_test)
print('\n')
print(confusion_matrix(y_test,grid_predict))
print(classification_report(y_test,grid_predict))



[[31  0  0]
 [ 0 38  1]
 [ 1  6 30]]
              precision    recall  f1-score   support

        HIGH       0.97      1.00      0.98        31
         LOW       0.86      0.97      0.92        39
      MEDIUM       0.97      0.81      0.88        37

    accuracy                           0.93       107
   macro avg       0.93      0.93      0.93       107
weighted avg       0.93      0.93      0.92       107



In [17]:
# HIGH CORR TOP 4 WITH NO PARAMETER ADJUSTMENT BEST

In [18]:
grid.best_estimator_

SVC(C=1, gamma=0.01)

In [19]:
y_predict = y_predict
ex6 = pd.concat([pd.DataFrame(confusion_matrix(y_test,y_predict,labels=['LOW','MEDIUM','HIGH']),index=['LOW','MEDIUM','HIGH'],columns=['LOW','MEDIUM','HIGH']),
pd.DataFrame(classification_report(y_test,y_predict,labels=['LOW','MEDIUM','HIGH'],output_dict=True)).transpose()],axis=1)
ex6.set_index([[text,text,text,text,text,text],ex6.index],inplace=True)
ex6

LOW  MEDIUM  \
HIGH CORR TOP 4 PICKED 9,11,10,5 (4 TOTAL ITEMS) LOW           34.0     5.0   
                                                 MEDIUM         5.0    32.0   
                                                 HIGH           0.0     2.0   
                                                 accuracy       NaN     NaN   
                                                 macro avg      NaN     NaN   
                                                 weighted avg   NaN     NaN   

                                                               HIGH  \
HIGH CORR TOP 4 PICKED 9,11,10,5 (4 TOTAL ITEMS) LOW            0.0   
                                                 MEDIUM         0.0   
                                                 HIGH          29.0   
                                                 accuracy       NaN   
                                                 macro avg      NaN   
                                                 weighted avg   NaN   

                                                               precision  \
HIGH CORR TOP 4 PICKED 9,11,10,5 (4 TOTAL ITEMS) LOW            0.871795   
                                                 MEDIUM         0.820513   
                                                 HIGH           1.000000   
                                                 accuracy       0.887850   
                                                 macro avg      0.897436   
                                                 weighted avg   0.891205   

                                                                 recall  \
HIGH CORR TOP 4 PICKED 9,11,10,5 (4 TOTAL ITEMS) LOW           0.871795   
                                                 MEDIUM        0.864865   
                                                 HIGH          0.935484   
                                                 accuracy      0.887850   
                                                 macro avg     0.890715   
                                                 weighted avg  0.887850   

                                                               f1-score  \
HIGH CORR TOP 4 PICKED 9,11,10,5 (4 TOTAL ITEMS) LOW           0.871795   
                                                 MEDIUM        0.842105   
                                                 HIGH          0.966667   
                                                 accuracy      0.887850   
                                                 macro avg     0.893522   
                                                 weighted avg  0.889015   

                                                                 support  
HIGH CORR TOP 4 PICKED 9,11,10,5 (4 TOTAL ITEMS) LOW            39.00000  
                                                 MEDIUM         37.00000  
                                                 HIGH           31.00000  
                                                 accuracy        0.88785  
                                                 macro avg     107.00000  
                                                 weighted avg  107.00000

In [20]:
# HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS)

In [21]:
X = df[['Item 5','Item 8','Item 9','Item 10','Item 11']]
y = df['Assessment of Risk']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=rs)

In [22]:
# NO PARAMETER ADJUSTMENT
model = SVC()
model.fit(X_train,y_train)
y_predict = model.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

[[30  0  1]
 [ 0 39  0]
 [ 1  1 35]]
              precision    recall  f1-score   support

        HIGH       0.97      0.97      0.97        31
         LOW       0.97      1.00      0.99        39
      MEDIUM       0.97      0.95      0.96        37

    accuracy                           0.97       107
   macro avg       0.97      0.97      0.97       107
weighted avg       0.97      0.97      0.97       107



In [23]:
# WITH PARAMETER ADJUSTMENT
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001]}
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=0)
grid.fit(X_train,y_train)
grid_predict = grid.predict(X_test)
print('\n')
print(confusion_matrix(y_test,grid_predict))
print(classification_report(y_test,grid_predict))



[[30  0  1]
 [ 0 38  1]
 [ 1  1 35]]
              precision    recall  f1-score   support

        HIGH       0.97      0.97      0.97        31
         LOW       0.97      0.97      0.97        39
      MEDIUM       0.95      0.95      0.95        37

    accuracy                           0.96       107
   macro avg       0.96      0.96      0.96       107
weighted avg       0.96      0.96      0.96       107



In [24]:
# HIGH CORR TOP 5 WITH NO PARAMETER ADJUSTMENT BEST

In [25]:
grid.best_estimator_

SVC(C=1000, gamma=0.01)

In [26]:
y_predict = y_predict
ex2 = pd.concat([pd.DataFrame(confusion_matrix(y_test,y_predict,labels=['LOW','MEDIUM','HIGH']),index=['LOW','MEDIUM','HIGH'],columns=['LOW','MEDIUM','HIGH']),
pd.DataFrame(classification_report(y_test,y_predict,labels=['LOW','MEDIUM','HIGH'],output_dict=True)).transpose()],axis=1)
ex2.set_index([['HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS)','HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS)','HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS)','HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS)','HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS)','HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS)'],ex2.index],inplace=True)
ex2

LOW  MEDIUM  \
HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS) LOW           39.0     0.0   
                                                   MEDIUM         1.0    35.0   
                                                   HIGH           0.0     1.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   

                                                                 HIGH  \
HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS) LOW            0.0   
                                                   MEDIUM         1.0   
                                                   HIGH          30.0   
                                                   accuracy       NaN   
                                                   macro avg      NaN   
                                                   weighted avg   NaN   

                                                                 precision  \
HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS) LOW            0.975000   
                                                   MEDIUM         0.972222   
                                                   HIGH           0.967742   
                                                   accuracy       0.971963   
                                                   macro avg      0.971655   
                                                   weighted avg   0.971937   

                                                                   recall  \
HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS) LOW           1.000000   
                                                   MEDIUM        0.945946   
                                                   HIGH          0.967742   
                                                   accuracy      0.971963   
                                                   macro avg     0.971229   
                                                   weighted avg  0.971963   

                                                                 f1-score  \
HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS) LOW           0.987342   
                                                   MEDIUM        0.958904   
                                                   HIGH          0.967742   
                                                   accuracy      0.971963   
                                                   macro avg     0.971329   
                                                   weighted avg  0.971830   

                                                                    support  
HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS) LOW            39.000000  
                                                   MEDIUM         37.000000  
                                                   HIGH           31.000000  
                                                   accuracy        0.971963  
                                                   macro avg     107.000000  
                                                   weighted avg  107.000000

In [27]:
# HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL ITEMS)

In [28]:
X = df[['Item 5','Item 7','Item 8','Item 9','Item 10','Item 11']]
y = df['Assessment of Risk']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=rs)

In [29]:
# NO PARAMETER ADJUSTMENT
model = SVC()
model.fit(X_train,y_train)
y_predict = model.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

[[31  0  0]
 [ 0 39  0]
 [ 1  0 36]]
              precision    recall  f1-score   support

        HIGH       0.97      1.00      0.98        31
         LOW       1.00      1.00      1.00        39
      MEDIUM       1.00      0.97      0.99        37

    accuracy                           0.99       107
   macro avg       0.99      0.99      0.99       107
weighted avg       0.99      0.99      0.99       107



In [30]:
# WITH PARAMETER ADJUSTMENT
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001]}
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=0)
grid.fit(X_train,y_train)
grid_predict = grid.predict(X_test)
print('\n')
print(confusion_matrix(y_test,grid_predict))
print(classification_report(y_test,grid_predict))



[[31  0  0]
 [ 0 38  1]
 [ 1  0 36]]
              precision    recall  f1-score   support

        HIGH       0.97      1.00      0.98        31
         LOW       1.00      0.97      0.99        39
      MEDIUM       0.97      0.97      0.97        37

    accuracy                           0.98       107
   macro avg       0.98      0.98      0.98       107
weighted avg       0.98      0.98      0.98       107



In [31]:
# HIGH CORR TOP 6 WITH NO PARAMETER ADJUSTMENT BEST

In [32]:
grid.best_estimator_

SVC(C=100, gamma=0.01)

In [33]:
y_predict = y_predict
ex3 = pd.concat([pd.DataFrame(confusion_matrix(y_test,y_predict,labels=['LOW','MEDIUM','HIGH']),index=['LOW','MEDIUM','HIGH'],columns=['LOW','MEDIUM','HIGH']),
pd.DataFrame(classification_report(y_test,y_predict,labels=['LOW','MEDIUM','HIGH'],output_dict=True)).transpose()],axis=1)
ex3.set_index([['HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL ITEMS)','HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL ITEMS)','HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL ITEMS)','HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL ITEMS)','HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL ITEMS)','HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL ITEMS)'],ex3.index],inplace=True)
ex3

LOW  MEDIUM  \
HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL I... LOW           39.0     0.0   
                                                   MEDIUM         0.0    36.0   
                                                   HIGH           0.0     0.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   

                                                                 HIGH  \
HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL I... LOW            0.0   
                                                   MEDIUM         1.0   
                                                   HIGH          31.0   
                                                   accuracy       NaN   
                                                   macro avg      NaN   
                                                   weighted avg   NaN   

                                                                 precision  \
HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL I... LOW            1.000000   
                                                   MEDIUM         1.000000   
                                                   HIGH           0.968750   
                                                   accuracy       0.990654   
                                                   macro avg      0.989583   
                                                   weighted avg   0.990946   

                                                                   recall  \
HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL I... LOW           1.000000   
                                                   MEDIUM        0.972973   
                                                   HIGH          1.000000   
                                                   accuracy      0.990654   
                                                   macro avg     0.990991   
                                                   weighted avg  0.990654   

                                                                 f1-score  \
HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL I... LOW           1.000000   
                                                   MEDIUM        0.986301   
                                                   HIGH          0.984127   
                                                   accuracy      0.990654   
                                                   macro avg     0.990143   
                                                   weighted avg  0.990664   

                                                                    support  
HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL I... LOW            39.000000  
                                                   MEDIUM         37.000000  
                                                   HIGH           31.000000  
                                                   accuracy        0.990654  
                                                   macro avg     107.000000  
                                                   weighted avg  107.000000

In [34]:
# DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS)

In [35]:
X = df[['Item 4','Item 8','Item 10','Item 11','Item 12','Item 14']]
y = df['Assessment of Risk']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=rs)

In [36]:
# NO PARAMETER ADJUSTMENT
model = SVC()
model.fit(X_train,y_train)
y_predict = model.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

[[30  0  1]
 [ 0 38  1]
 [ 2  1 34]]
              precision    recall  f1-score   support

        HIGH       0.94      0.97      0.95        31
         LOW       0.97      0.97      0.97        39
      MEDIUM       0.94      0.92      0.93        37

    accuracy                           0.95       107
   macro avg       0.95      0.95      0.95       107
weighted avg       0.95      0.95      0.95       107



In [37]:
# WITH PARAMETER ADJUSTMENT
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001]}
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=0)
grid.fit(X_train,y_train)
grid_predict = grid.predict(X_test)
print('\n')
print(confusion_matrix(y_test,grid_predict))
print(classification_report(y_test,grid_predict))



[[28  0  3]
 [ 0 36  3]
 [ 1  0 36]]
              precision    recall  f1-score   support

        HIGH       0.97      0.90      0.93        31
         LOW       1.00      0.92      0.96        39
      MEDIUM       0.86      0.97      0.91        37

    accuracy                           0.93       107
   macro avg       0.94      0.93      0.93       107
weighted avg       0.94      0.93      0.94       107



In [38]:
#DS PRACTICAL PICK WITH 50/50 SPLIT WITH AND WITHOUT PARAMETER ADJUSTMENTS

In [39]:
grid.best_estimator_

SVC(C=1, gamma=1)

In [40]:
y_predict = y_predict
ex4 = pd.concat([pd.DataFrame(confusion_matrix(y_test,y_predict,labels=['LOW','MEDIUM','HIGH']),index=['LOW','MEDIUM','HIGH'],columns=['LOW','MEDIUM','HIGH']),
pd.DataFrame(classification_report(y_test,y_predict,labels=['LOW','MEDIUM','HIGH'],output_dict=True)).transpose()],axis=1)
ex4.set_index([['DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS)','DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS)','DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS)','DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS)','DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS)','DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS)'],ex4.index],inplace=True)
ex4

LOW  MEDIUM  \
DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS) LOW           38.0     1.0   
                                                  MEDIUM         1.0    34.0   
                                                  HIGH           0.0     1.0   
                                                  accuracy       NaN     NaN   
                                                  macro avg      NaN     NaN   
                                                  weighted avg   NaN     NaN   

                                                                HIGH  \
DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS) LOW            0.0   
                                                  MEDIUM         2.0   
                                                  HIGH          30.0   
                                                  accuracy       NaN   
                                                  macro avg      NaN   
                                                  weighted avg   NaN   

                                                                precision  \
DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS) LOW            0.974359   
                                                  MEDIUM         0.944444   
                                                  HIGH           0.937500   
                                                  accuracy       0.953271   
                                                  macro avg      0.952101   
                                                  weighted avg   0.953336   

                                                                  recall  \
DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS) LOW           0.974359   
                                                  MEDIUM        0.918919   
                                                  HIGH          0.967742   
                                                  accuracy      0.953271   
                                                  macro avg     0.953673   
                                                  weighted avg  0.953271   

                                                                f1-score  \
DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS) LOW           0.974359   
                                                  MEDIUM        0.931507   
                                                  HIGH          0.952381   
                                                  accuracy      0.953271   
                                                  macro avg     0.952749   
                                                  weighted avg  0.953173   

                                                                   support  
DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS) LOW            39.000000  
                                                  MEDIUM         37.000000  
                                                  HIGH           31.000000  
                                                  accuracy        0.953271  
                                                  macro avg     107.000000  
                                                  weighted avg  107.000000

In [41]:
# HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL ITEMS)

In [42]:
X = df[['Item 5','Item 6','Item 7','Item 8','Item 9','Item 10','Item 11']]
y = df['Assessment of Risk']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=rs)

In [43]:
# NO PARAMETER ADJUSTMENT
model = SVC()
model.fit(X_train,y_train)
y_predict = model.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

[[31  0  0]
 [ 0 39  0]
 [ 1  0 36]]
              precision    recall  f1-score   support

        HIGH       0.97      1.00      0.98        31
         LOW       1.00      1.00      1.00        39
      MEDIUM       1.00      0.97      0.99        37

    accuracy                           0.99       107
   macro avg       0.99      0.99      0.99       107
weighted avg       0.99      0.99      0.99       107



In [44]:
# WITH PARAMETER ADJUSTMENT
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001]}
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=0)
grid.fit(X_train,y_train)
grid_predict = grid.predict(X_test)
print('\n')
print(confusion_matrix(y_test,grid_predict))
print(classification_report(y_test,grid_predict))



[[31  0  0]
 [ 0 39  0]
 [ 1  0 36]]
              precision    recall  f1-score   support

        HIGH       0.97      1.00      0.98        31
         LOW       1.00      1.00      1.00        39
      MEDIUM       1.00      0.97      0.99        37

    accuracy                           0.99       107
   macro avg       0.99      0.99      0.99       107
weighted avg       0.99      0.99      0.99       107



In [45]:
# HIGH CORR TOP 7 WITH PARAMETER ADJUSTMENTS BEST

In [46]:
grid.best_estimator_

SVC(C=1, gamma=0.1)

In [47]:
y_predict = y_predict
ex5 = pd.concat([pd.DataFrame(confusion_matrix(y_test,y_predict,labels=['LOW','MEDIUM','HIGH']),index=['LOW','MEDIUM','HIGH'],columns=['LOW','MEDIUM','HIGH']),
pd.DataFrame(classification_report(y_test,y_predict,labels=['LOW','MEDIUM','HIGH'],output_dict=True)).transpose()],axis=1)
ex5.set_index([['HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL ITEMS)','HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL ITEMS)','HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL ITEMS)','HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL ITEMS)','HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL ITEMS)','HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL ITEMS)'],ex5.index],inplace=True)
ex5

LOW  MEDIUM  \
HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL... LOW           39.0     0.0   
                                                   MEDIUM         0.0    36.0   
                                                   HIGH           0.0     0.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   

                                                                 HIGH  \
HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL... LOW            0.0   
                                                   MEDIUM         1.0   
                                                   HIGH          31.0   
                                                   accuracy       NaN   
                                                   macro avg      NaN   
                                                   weighted avg   NaN   

                                                                 precision  \
HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL... LOW            1.000000   
                                                   MEDIUM         1.000000   
                                                   HIGH           0.968750   
                                                   accuracy       0.990654   
                                                   macro avg      0.989583   
                                                   weighted avg   0.990946   

                                                                   recall  \
HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL... LOW           1.000000   
                                                   MEDIUM        0.972973   
                                                   HIGH          1.000000   
                                                   accuracy      0.990654   
                                                   macro avg     0.990991   
                                                   weighted avg  0.990654   

                                                                 f1-score  \
HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL... LOW           1.000000   
                                                   MEDIUM        0.986301   
                                                   HIGH          0.984127   
                                                   accuracy      0.990654   
                                                   macro avg     0.990143   
                                                   weighted avg  0.990664   

                                                                    support  
HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL... LOW            39.000000  
                                                   MEDIUM         37.000000  
                                                   HIGH           31.000000  
                                                   accuracy        0.990654  
                                                   macro avg     107.000000  
                                                   weighted avg  107.000000

In [48]:
# HIGH CORR TOP 8 PICKED 9,11,10,5,8,7,6,12 (8 TOTAL ITEMS)

In [49]:
X = df[['Item 5','Item 6','Item 7','Item 8','Item 9','Item 10','Item 11','Item 12']]
y = df['Assessment of Risk']
text = 'HIGH CORR TOP 8 PICKED 9,11,10,5,8,7,6,12 (8 TOTAL ITEMS)'

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=rs)

In [50]:
# NO PARAMETER ADJUSTMENT
model = SVC()
model.fit(X_train,y_train)
y_predict = model.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

[[31  0  0]
 [ 0 39  0]
 [ 1  3 33]]
              precision    recall  f1-score   support

        HIGH       0.97      1.00      0.98        31
         LOW       0.93      1.00      0.96        39
      MEDIUM       1.00      0.89      0.94        37

    accuracy                           0.96       107
   macro avg       0.97      0.96      0.96       107
weighted avg       0.96      0.96      0.96       107



In [51]:
# WITH PARAMETER ADJUSTMENT
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001]}
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=0)
grid.fit(X_train,y_train)
grid_predict = grid.predict(X_test)
print('\n')
print(confusion_matrix(y_test,grid_predict))
print(classification_report(y_test,grid_predict))



[[31  0  0]
 [ 0 39  0]
 [ 1  3 33]]
              precision    recall  f1-score   support

        HIGH       0.97      1.00      0.98        31
         LOW       0.93      1.00      0.96        39
      MEDIUM       1.00      0.89      0.94        37

    accuracy                           0.96       107
   macro avg       0.97      0.96      0.96       107
weighted avg       0.96      0.96      0.96       107



In [52]:
# HIGH CORR TOP 8 WITH NO PARAMETER ADJUSTMENT BEST

In [53]:
grid.best_estimator_

SVC(C=1, gamma=0.1)

In [54]:
y_predict = y_predict
ex7 = pd.concat([pd.DataFrame(confusion_matrix(y_test,y_predict,labels=['LOW','MEDIUM','HIGH']),index=['LOW','MEDIUM','HIGH'],columns=['LOW','MEDIUM','HIGH']),
pd.DataFrame(classification_report(y_test,y_predict,labels=['LOW','MEDIUM','HIGH'],output_dict=True)).transpose()],axis=1)
ex7.set_index([[text,text,text,text,text,text],ex7.index],inplace=True)
ex7

LOW  MEDIUM  \
HIGH CORR TOP 8 PICKED 9,11,10,5,8,7,6,12 (8 TO... LOW           39.0     0.0   
                                                   MEDIUM         3.0    33.0   
                                                   HIGH           0.0     0.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   

                                                                 HIGH  \
HIGH CORR TOP 8 PICKED 9,11,10,5,8,7,6,12 (8 TO... LOW            0.0   
                                                   MEDIUM         1.0   
                                                   HIGH          31.0   
                                                   accuracy       NaN   
                                                   macro avg      NaN   
                                                   weighted avg   NaN   

                                                                 precision  \
HIGH CORR TOP 8 PICKED 9,11,10,5,8,7,6,12 (8 TO... LOW            0.928571   
                                                   MEDIUM         1.000000   
                                                   HIGH           0.968750   
                                                   accuracy       0.962617   
                                                   macro avg      0.965774   
                                                   weighted avg   0.964912   

                                                                   recall  \
HIGH CORR TOP 8 PICKED 9,11,10,5,8,7,6,12 (8 TO... LOW           1.000000   
                                                   MEDIUM        0.891892   
                                                   HIGH          1.000000   
                                                   accuracy      0.962617   
                                                   macro avg     0.963964   
                                                   weighted avg  0.962617   

                                                                 f1-score  \
HIGH CORR TOP 8 PICKED 9,11,10,5,8,7,6,12 (8 TO... LOW           0.962963   
                                                   MEDIUM        0.942857   
                                                   HIGH          0.984127   
                                                   accuracy      0.962617   
                                                   macro avg     0.963316   
                                                   weighted avg  0.962142   

                                                                    support  
HIGH CORR TOP 8 PICKED 9,11,10,5,8,7,6,12 (8 TO... LOW            39.000000  
                                                   MEDIUM         37.000000  
                                                   HIGH           31.000000  
                                                   accuracy        0.962617  
                                                   macro avg     107.000000  
                                                   weighted avg  107.000000

In [55]:
# HIGH CORR TOP 9 PICKED 9,11,10,5,8,7,6,12,13 (9 TOTAL ITEMS)

In [56]:
X = df[['Item 5','Item 6','Item 7','Item 8','Item 9','Item 10','Item 11','Item 12','Item 13']]
y = df['Assessment of Risk']
text = 'HIGH CORR TOP 9 PICKED 9,11,10,5,8,7,6,12,13 (9 TOTAL ITEMS)'

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=rs)

In [57]:
# NO PARAMETER ADJUSTMENT
model = SVC()
model.fit(X_train,y_train)
y_predict = model.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

[[31  0  0]
 [ 0 39  0]
 [ 1  3 33]]
              precision    recall  f1-score   support

        HIGH       0.97      1.00      0.98        31
         LOW       0.93      1.00      0.96        39
      MEDIUM       1.00      0.89      0.94        37

    accuracy                           0.96       107
   macro avg       0.97      0.96      0.96       107
weighted avg       0.96      0.96      0.96       107



In [58]:
# WITH PARAMETER ADJUSTMENT
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001]}
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=0)
grid.fit(X_train,y_train)
grid_predict = grid.predict(X_test)
print('\n')
print(confusion_matrix(y_test,grid_predict))
print(classification_report(y_test,grid_predict))



[[31  0  0]
 [ 0 39  0]
 [ 1  0 36]]
              precision    recall  f1-score   support

        HIGH       0.97      1.00      0.98        31
         LOW       1.00      1.00      1.00        39
      MEDIUM       1.00      0.97      0.99        37

    accuracy                           0.99       107
   macro avg       0.99      0.99      0.99       107
weighted avg       0.99      0.99      0.99       107



In [59]:
# HIGH CORR TOP 9 WITH NO PARAMETER ADJUSTMENT BEST

In [60]:
grid.best_estimator_

SVC(C=1, gamma=0.1)

In [61]:
y_predict = y_predict
ex8 = pd.concat([pd.DataFrame(confusion_matrix(y_test,y_predict,labels=['LOW','MEDIUM','HIGH']),index=['LOW','MEDIUM','HIGH'],columns=['LOW','MEDIUM','HIGH']),
pd.DataFrame(classification_report(y_test,y_predict,labels=['LOW','MEDIUM','HIGH'],output_dict=True)).transpose()],axis=1)
ex8.set_index([[text,text,text,text,text,text],ex8.index],inplace=True)
ex8

LOW  MEDIUM  \
HIGH CORR TOP 9 PICKED 9,11,10,5,8,7,6,12,13 (9... LOW           39.0     0.0   
                                                   MEDIUM         3.0    33.0   
                                                   HIGH           0.0     0.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   

                                                                 HIGH  \
HIGH CORR TOP 9 PICKED 9,11,10,5,8,7,6,12,13 (9... LOW            0.0   
                                                   MEDIUM         1.0   
                                                   HIGH          31.0   
                                                   accuracy       NaN   
                                                   macro avg      NaN   
                                                   weighted avg   NaN   

                                                                 precision  \
HIGH CORR TOP 9 PICKED 9,11,10,5,8,7,6,12,13 (9... LOW            0.928571   
                                                   MEDIUM         1.000000   
                                                   HIGH           0.968750   
                                                   accuracy       0.962617   
                                                   macro avg      0.965774   
                                                   weighted avg   0.964912   

                                                                   recall  \
HIGH CORR TOP 9 PICKED 9,11,10,5,8,7,6,12,13 (9... LOW           1.000000   
                                                   MEDIUM        0.891892   
                                                   HIGH          1.000000   
                                                   accuracy      0.962617   
                                                   macro avg     0.963964   
                                                   weighted avg  0.962617   

                                                                 f1-score  \
HIGH CORR TOP 9 PICKED 9,11,10,5,8,7,6,12,13 (9... LOW           0.962963   
                                                   MEDIUM        0.942857   
                                                   HIGH          0.984127   
                                                   accuracy      0.962617   
                                                   macro avg     0.963316   
                                                   weighted avg  0.962142   

                                                                    support  
HIGH CORR TOP 9 PICKED 9,11,10,5,8,7,6,12,13 (9... LOW            39.000000  
                                                   MEDIUM         37.000000  
                                                   HIGH           31.000000  
                                                   accuracy        0.962617  
                                                   macro avg     107.000000  
                                                   weighted avg  107.000000

In [62]:
# HIGH CORR TOP 10 PICKED 9,11,10,5,8,7,6,12,13,4 (10 TOTAL ITEMS)

In [63]:
X = df[['Item 4','Item 5','Item 6','Item 7','Item 8','Item 9','Item 10','Item 11','Item 12','Item 13']]
y = df['Assessment of Risk']
text = 'HIGH CORR TOP 10 PICKED 9,11,10,5,8,7,6,12,13,4 (10 TOTAL ITEMS)'

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=rs)

In [64]:
# NO PARAMETER ADJUSTMENT
model = SVC()
model.fit(X_train,y_train)
y_predict = model.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

[[31  0  0]
 [ 0 38  1]
 [ 1  0 36]]
              precision    recall  f1-score   support

        HIGH       0.97      1.00      0.98        31
         LOW       1.00      0.97      0.99        39
      MEDIUM       0.97      0.97      0.97        37

    accuracy                           0.98       107
   macro avg       0.98      0.98      0.98       107
weighted avg       0.98      0.98      0.98       107



In [65]:
# WITH PARAMETER ADJUSTMENT
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001]}
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=0)
grid.fit(X_train,y_train)
grid_predict = grid.predict(X_test)
print('\n')
print(confusion_matrix(y_test,grid_predict))
print(classification_report(y_test,grid_predict))



[[30  0  1]
 [ 0 38  1]
 [ 1  0 36]]
              precision    recall  f1-score   support

        HIGH       0.97      0.97      0.97        31
         LOW       1.00      0.97      0.99        39
      MEDIUM       0.95      0.97      0.96        37

    accuracy                           0.97       107
   macro avg       0.97      0.97      0.97       107
weighted avg       0.97      0.97      0.97       107



In [66]:
# HIGH CORR TOP 10 WITH PARAMETER ADJUSTMENT BEST

In [67]:
grid.best_estimator_

SVC(C=1, gamma=0.1)

In [68]:
# HOWEVER, I WILL KEEP AS WITHOUT PARAMETER ADJUSTMENT

In [69]:
y_predict = y_predict
ex9 = pd.concat([pd.DataFrame(confusion_matrix(y_test,y_predict,labels=['LOW','MEDIUM','HIGH']),index=['LOW','MEDIUM','HIGH'],columns=['LOW','MEDIUM','HIGH']),
pd.DataFrame(classification_report(y_test,y_predict,labels=['LOW','MEDIUM','HIGH'],output_dict=True)).transpose()],axis=1)
ex9.set_index([[text,text,text,text,text,text],ex9.index],inplace=True)
ex9

LOW  MEDIUM  \
HIGH CORR TOP 10 PICKED 9,11,10,5,8,7,6,12,13,4... LOW           38.0     1.0   
                                                   MEDIUM         0.0    36.0   
                                                   HIGH           0.0     0.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   

                                                                 HIGH  \
HIGH CORR TOP 10 PICKED 9,11,10,5,8,7,6,12,13,4... LOW            0.0   
                                                   MEDIUM         1.0   
                                                   HIGH          31.0   
                                                   accuracy       NaN   
                                                   macro avg      NaN   
                                                   weighted avg   NaN   

                                                                 precision  \
HIGH CORR TOP 10 PICKED 9,11,10,5,8,7,6,12,13,4... LOW            1.000000   
                                                   MEDIUM         0.972973   
                                                   HIGH           0.968750   
                                                   accuracy       0.981308   
                                                   macro avg      0.980574   
                                                   weighted avg   0.981600   

                                                                   recall  \
HIGH CORR TOP 10 PICKED 9,11,10,5,8,7,6,12,13,4... LOW           0.974359   
                                                   MEDIUM        0.972973   
                                                   HIGH          1.000000   
                                                   accuracy      0.981308   
                                                   macro avg     0.982444   
                                                   weighted avg  0.981308   

                                                                 f1-score  \
HIGH CORR TOP 10 PICKED 9,11,10,5,8,7,6,12,13,4... LOW           0.987013   
                                                   MEDIUM        0.972973   
                                                   HIGH          0.984127   
                                                   accuracy      0.981308   
                                                   macro avg     0.981371   
                                                   weighted avg  0.981322   

                                                                    support  
HIGH CORR TOP 10 PICKED 9,11,10,5,8,7,6,12,13,4... LOW            39.000000  
                                                   MEDIUM         37.000000  
                                                   HIGH           31.000000  
                                                   accuracy        0.981308  
                                                   macro avg     107.000000  
                                                   weighted avg  107.000000

In [70]:
finalex = pd.concat([ex1,ex6,ex2,ex3,ex4,ex5,ex7,ex8,ex9])
finalex

LOW  MEDIUM  \
Original                                           LOW           39.0     0.0   
                                                   MEDIUM         0.0    36.0   
                                                   HIGH           0.0     0.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   
HIGH CORR TOP 4 PICKED 9,11,10,5 (4 TOTAL ITEMS)   LOW           34.0     5.0   
                                                   MEDIUM         5.0    32.0   
                                                   HIGH           0.0     2.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   
HIGH CORR TOP 5 PICKED 9,11,10,5,8 (5 TOTAL ITEMS) LOW           39.0     0.0   
                                                   MEDIUM         1.0    35.0   
                                                   HIGH           0.0     1.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   
HIGH CORR TOP 6 PICKED 9,11,10,5,8,7 (6 TOTAL I... LOW           39.0     0.0   
                                                   MEDIUM         0.0    36.0   
                                                   HIGH           0.0     0.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   
DS PRACTICAL PICK 14,12,11,10,8,4 (6 TOTAL ITEMS)  LOW           38.0     1.0   
                                                   MEDIUM         1.0    34.0   
                                                   HIGH           0.0     1.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   
HIGH CORR TOP 7 PICKED 9,11,10,5,8,7,6 (7 TOTAL... LOW           39.0     0.0   
                                                   MEDIUM         0.0    36.0   
                                                   HIGH           0.0     0.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   
HIGH CORR TOP 8 PICKED 9,11,10,5,8,7,6,12 (8 TO... LOW           39.0     0.0   
                                                   MEDIUM         3.0    33.0   
                                                   HIGH           0.0     0.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   
HIGH CORR TOP 9 PICKED 9,11,10,5,8,7,6,12,13 (9... LOW           39.0     0.0   
                                                   MEDIUM         3.0    33.0   
                                                   HIGH           0.0     0.0   
                                                   accuracy       NaN     NaN   
                                                   macro avg      NaN     NaN   
                                                   weighted avg   NaN     NaN   
HIGH CORR TOP 10 PICKED 9,11,10,5,8,7,6,12,13,4... LOW           38.0     1.0   
                

In [71]:
finalex.to_excel(r'C:\Users\krunk\OneDrive\Documents\CPSC 597\Project Data\BBS Machine Learning Data Collection (Support Vector Machine).xlsx',sheet_name='SVM')